---
# docker_install.yml

# - set_fact:
#     updated_sumologic_docker_options: "{{ sumologic_docker_options }} -v /var/log/sa:/var/log/sa"
#   when: sumologic_do_sysstat == "yes"
#   tags:
#     - sumologic
#     - sumologic_docker

# - debug: msg="{{ updated_sumologic_docker_options }}"
#   tags:
#     - sumologic
#     - sumologic_docker

- name: install systemd unit for sumologic
  template:
    src: sumologic-collector.service
    dest: "{{ syslog_units_directory }}/sumologic-collector.service"
    mode: 0700
  notify:
    - Restart SumoCollector
  tags: [sumologic, sumologic_docker]

- name: install systemd unit for journalctl to customize docker jounald logs
  template:
    src: journalctl_syslog.service
    dest: "{{ syslog_units_directory }}/journalctl_syslog.service"
    mode: 0700
  notify:
    - Restart journalctl_syslog service
  tags: [sumologic, sumologic_docker]
  when: sumologic_install_journal_syslog_service == "yes"

- name: start systemd unit for sumologic-collector
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - sumologic-collector.service
  tags: [sumologic, sumologic_docker]

- name: start systemd unit for journalctl_syslog
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - journalctl_syslog.service
  tags: [sumologic, sumologic_docker]
  when: sumologic_install_journal_syslog_service == "yes"

- name: force stop journalctl_syslog service
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items:
    - journalctl_syslog.service
  tags: [sumologic, sumologic_docker]
  when: (sumologic_force_restart == "yes") and (sumologic_install_method != "docker")
