---
## https://help.sumologic.com/Send_Data/Installed_Collectors/05Reference_Information_for_Collector_Installation/05Set_the_Run_As_User_for_a_Collector

- name: ensure sumo user is presents
  user:
    name: "{{ sumologic_collector_user }}"
    comment: "Sumologic collector user"
    state: present
    system: yes

- name: gave read/write access to sumo user
  file:
    path: "{{ sumologic_collector_root }}"
    owner: "{{ sumologic_collector_user }}"
    recurse: yes
    state: directory

- name: check current collector service file
  command: "egrep '^RUN_AS_USER={{ sumologic_collector_user }}' /etc/init.d/collector"
  register: svcfile
  changed_when: false
  ignore_errors: true

- block:
    - name: Remove collector service
      command: "{{ sumologic_collector_root }}/collector remove"
      args:
        removes: /etc/init.d/collector

    - name: configure collector install with sumo user
      replace:
        dest: "{{ sumologic_collector_root }}/collector"
        regexp: '^#RUN_AS_USER=.*'
        replace: "RUN_AS_USER={{ sumologic_collector_user }}"
        backup: yes

    - name: Install collector service
      command: "{{ sumologic_collector_root }}/collector install"
      args:
        creates: /etc/init.d/collector
      notify:
        - Restart SumoCollector
  when: not svcfile.stdout
