---

- name: Restart SumoCollector
  service:
    name: "{{ sumologic_collector_service_name }}"
    state: stopped
    use: service
  tags: [sumologic, sumologic-collector]
  notify: 'Restart SumoCollector wait'
  changed_when: True

# attempt to avoid collectore uuid suffixes caused when
# restart happens before sumo cloud recognizes old collector is gone.
- name: Restart SumoCollector wait
  pause:
    seconds: 10
  tags: [sumologic, sumologic-collector]
  notify: Restart SumoCollector start
  changed_when: True

- name: Restart SumoCollector start
  service:
    name: "{{ sumologic_collector_service_name }}"
    state: started
    use: service
  tags: [sumologic, sumologic-collector]
  changed_when: True
## for CI testing with invalid credentials
  ignore_errors: true

- name: Restart journalctl_syslog service
  service:
    name: journalctl_syslog
    state: restarted
  tags: [sumologic, sumologic-collector]
